[package]
name = "lore-proto"
# Crate version is used for proto-artifactory workflow
version = "0.1.60"
edition = "2024"
publish = false

[dependencies]
lore-base = { path = "../lore-base" }

prost = "0.14.1"

prost-types = "0.14.1"

tonic = { version = "0.14.2", default-features = false, features = ["codegen", "router", "server", "tls-native-roots"] }

tonic-prost = "0.14.2"


[build-dependencies]
tonic-prost-build = "0.14.2"

