[package]
name = "lore-credential"
edition = "2024"
version.workspace = true
publish = false

[lib]
name = "lore_credential"

[dependencies]
base64 = "0.22.1"

jsonwebtoken = "9.3.1"

keyring = { version = "3.6.3", features = [ "apple-native", "windows-native", "linux-native", ] }

lore-base = { path = "../lore-base" }

lore-error-set = { path = "../lore-error-set" }

ring = "0.17.14"

serde = { version = "1.0.219", default-features = false, features = ["derive"] }

serde_with = { version = "3.14.0", default-features = false, features = ["alloc", "macros"] }

thiserror = "2.0.16"

tokio = { version = "1.47.1", features = [ "fs", "io-util", "macros", "net", "parking_lot", "rt", "rt-multi-thread", "signal", "sync", "time", ] }

toml = "0.9.5"

url = "2.5.7"

zerocopy = { version = "0.8.26", features = [ "derive", "alloc", "simd", ] }


[features]
trace_log = ["lore-base/trace_log"]

[target.'cfg(target_family = "windows")'.dependencies]
windows-sys = "0.61.0"

