[package]
name = "lore-client"
edition = "2024"
version.workspace = true
publish = false

[dependencies]
anstream = "0.6.20"

anstyle = "1.0.11"

chrono = { version = "0.4.42", default-features = false, features = ["alloc", "clock"] }

clap = { version = "4.5.47", features = ["derive", "string", "unicode"] }

clap-markdown = "0.1.5"

clap_complete = { version = "4.5.47" }
libc = "0.2.175"

parking_lot = { version = "0.12.4", features = ["arc_lock"] }

serde = { version = "1.0.219", default-features = false, features = ["derive"] }

serde_json = { version = "1.0.143", default-features = false }

thiserror = "2.0.16"

tokio = { version = "1.47.1", features = [ "fs", "io-util", "macros", "net", "parking_lot", "rt", "rt-multi-thread", "signal", "sync", "time", ] }

toml = "0.9.5"


lore = { path = "../lore" }

lore-base = { path = "../lore-base" }

lore-error-set = { path = "../lore-error-set" }

lore-revision = { path = "../lore-revision" }


[target.'cfg(target_family = "windows")'.dependencies]
windows-sys = "0.61.0"


[features]
default = []
oodle = ["lore/oodle"]

[build-dependencies]
vergen = { version = "9.0.6", default-features = false, features = ["cargo", "rustc", "build", "si"] }

anyhow = "1.0.103"

winresource = "0.1.23"

[[bin]]
name = "lore"
path = "src/cli/main.rs"
test = false
doctest = false
bench = false
doc = false
harness = false

[lib]
name = "lore_client"
path = "src/cli/lib.rs"

[package.metadata.winresource]
OriginalFilename = "lore.exe"
ProductName = "Lore"
FileDescription = "Lore CLI"
LegalCopyright = "Copyright Epic Games, Inc."
