[package]
name = "lore-error-set"
version = "0.1.0"
edition = "2021"
description = "Composable, traceable error handling for Rust"
publish = false

[features]
default = ["track-locations"]
track-locations = []

[dependencies]
lore-error-set-macro = { path = "../lore-error-set-macro" }


[dev-dependencies]
thiserror = "2.0.16"

trybuild = "1"

